BEGIN;

-- Table: production.sites

CREATE TABLE IF NOT EXISTS production.sites
(
    site_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    agency character varying(255) COLLATE pg_catalog."default",
    geometry geometry(Point,4326) NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sites_pkey PRIMARY KEY (site_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS production.sites
    OWNER to app_admin;


-- Table: production.usgs_sites

CREATE TABLE IF NOT EXISTS production.usgs_sites
(
    dst_offset bigint NOT NULL,
    network character varying(255) COLLATE pg_catalog."default",
    site_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    site_uses_dst boolean NOT NULL,
    time_zone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    time_zone_uses_dst boolean NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    site_id bigint NOT NULL,
    CONSTRAINT usgs_sites_pkey PRIMARY KEY (site_id),
    CONSTRAINT uk4su68fjactjoj2fn4awr2o6sv UNIQUE (site_number),
    CONSTRAINT fkgo122vf4ftinrugxbg53dqvcb FOREIGN KEY (site_id)
        REFERENCES production.sites (site_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS production.usgs_sites
    OWNER to app_admin;

-- Table: production.data_series

CREATE TABLE IF NOT EXISTS production.data_series
(
    data_series_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean,
    description character varying(255) COLLATE pg_catalog."default",
    param_cd smallint NOT NULL,
    units character varying(255) COLLATE pg_catalog."default",
    site bigint NOT NULL,
    CONSTRAINT data_series_pkey PRIMARY KEY (data_series_id),
    CONSTRAINT fktiy860ge8j0pelnjbrciij81 FOREIGN KEY (site)
        REFERENCES production.sites (site_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT data_series_param_cd_check CHECK (param_cd >= 0 AND param_cd <= 2)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS production.data_series
    OWNER to app_admin;


-- Table: production.instant_values

CREATE TABLE IF NOT EXISTS production.instant_values
(
    instant_value_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    original_offset character varying(255) COLLATE pg_catalog."default" NOT NULL,
    time_utc timestamp(6) without time zone NOT NULL,
    value double precision NOT NULL,
    data_series bigint NOT NULL,
    CONSTRAINT instant_values_pkey PRIMARY KEY (instant_value_id),
    CONSTRAINT ukm5e0u27hawa2rg1dc5tcbe1sg UNIQUE (time_utc, original_offset, data_series),
    CONSTRAINT fkhf6w5y7n5p01txv8w0hkovbbl FOREIGN KEY (data_series)
        REFERENCES production.data_series (data_series_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS production.instant_values
    OWNER to app_admin;

COMMIT;